<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU</Platforms>
    <Authors>Travis J. Gutjahr</Authors>
	<Company>$(Authors)</Company>
    <Copyright>Copyright © 2025 $(Authors)</Copyright>
    <Product>JSON Server UI Plugin</Product>
    <Description>A plugin that runs a light-weight Kestrel web server to output the values provided by the loaded Provider Plugin in JSON format.</Description>
    <Version>3.1.0</Version>
    <FileVersion>3.1.0</FileVersion>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <DebugType>embedded</DebugType>
    <!-- net5.0-windows had to be hardcoded here because this project reports $(TargetFramework) as netstandard2.0 (rightfully so) and I am not sure how this project's csproj can auto-detect another project's framework version to copy it to the appropriate folder so we're just... hardcoding this. -->
    <CopyDestionationPath>$(SolutionDir)..\..\SpeedRunTool\SRTHost\SRTHost\bin\$(Configuration)\net5.0-windows\plugins</CopyDestionationPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SamplePages\Quickturn96\re2-srt-display.html" />
    <None Remove="SamplePages\Squirrelies\Sample-RE2R-RE3R-JSONDisplayPage.html" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SamplePages\Quickturn96\re2-srt-display.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="SamplePages\Squirrelies\Sample-RE2R-RE3R-JSONDisplayPage.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
	
  <Target Name="CopyOutputToDestination" AfterTargets="AfterBuild">
    <ItemGroup>
      <OutputFiles Include="$(OutDir)**\*"></OutputFiles>
    </ItemGroup>
    <Message Text="Copying files: @(OutputFiles)" Importance="high" />
    <Copy SourceFiles="@(OutputFiles)" DestinationFolder="$(CopyDestionationPath)\$(ProjectName)\%(RecursiveDir)" OverwriteReadOnlyFiles="true"></Copy>
  </Target>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.3.0">
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.3.0">
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0">
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.3.0">
    </PackageReference>
    <PackageReference Include="System.Text.Json" Version="9.0.2">
    </PackageReference>
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\SpeedRunTool\SRTHost\SRTPluginBase\SRTPluginBase.csproj">
			<Private>false</Private>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>
</Project>
